Repository southworks/botframework-solutions, pull requests merged in 2020-02, with the labels that each got.

#217 Add enhancedBotFrameworkSkill file
  sdk/typescript/libraries/botbuilder-solutions/src/skills/enhancedBotFrameworkSkill.ts
  sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
Labels: review wanted

#214 Add skillsConfiguration file
  sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
  sdk/typescript/libraries/botbuilder-solutions/src/skills/skillsConfiguration.ts
Labels: review wanted

#215 Add skillDialogArgs file
  sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
  sdk/typescript/libraries/botbuilder-solutions/src/skills/skillDialogArgs.ts
Labels: review wanted

#216 Add skillConversationIdFactory file
  sdk/typescript/libraries/botbuilder-solutions/src/skills/index.ts
  sdk/typescript/libraries/botbuilder-solutions/src/skills/skillConversationIdFactory.ts
Labels: review wanted

#218 Update multiProviderAuthDialog
  sdk/typescript/libraries/botbuilder-solutions/src/authentication/multiProviderAuthDialog.ts
Labels: review wanted

#220 Update switchSkillDialogOptions
  sdk/typescript/libraries/botbuilder-solutions/src/skills/dialogs/switchSkillDialogOptions.ts
Labels: review wanted

#228 [TypeScript] GA SDK Skill Migration - Update Startup and Controller
  templates/typescript/samples/sample-skill/src/index.ts
Labels: PR: reviewed-approved

#229 [TypeScript] GA SDK Skill Migration - Create Extensions Folder
  templates/typescript/samples/sample-skill/src/extensions/turnContextEx.ts
Labels: PR: reviewed-approved

#225 [TypeScript] GA SDK Skill Migration - Update Adapters
  templates/typescript/samples/sample-skill/src/adapters/customSkillAdapter.ts
  templates/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-skill/src/adapters/index.ts
Labels: PR: reviewed-approved

#233 [GA Skills SDK][Virtual Assistant] Create AllowedCallersClaimsValidator
  templates/typescript/generator-botbuilder-assistant/generators/app/templates/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/samples/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
Labels: PR: review-wanted

#234 [GA Skills SDK][Virtual Assistant] Update SkillController
  templates/typescript/samples/sample-assistant/src/index.ts
Labels: PR: review-wanted

#230 [GA Skills SDK][Skill] Update Dialogs folder
  templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-skill/src/dialogs/sampleAction.ts
Labels: PR: reviewed-approved
