Repository southworks/botframework-solutions, pull requests merged in 2020-03, with the labels that each got.

#240 [TypeScript][0.8] Skill Migration - Update Bots Folder
  templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
Labels: PR: reviewed-approved

#235 [GA Skills SDK][Virtual Assistant] Update DefaultActivityHandler
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
Labels: PR: reviewed-approved

#226 [GA Skills SDK][Virtual Assistant] Update index.ts
  templates/typescript/samples/sample-assistant/src/appsettings.json
  templates/typescript/samples/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/src/services/botSettings.ts
Labels: PR: reviewed-approved

#238 [GA Skills SDK][Virtual Assistant] Update DefaultAdapter
  templates/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts
Labels: PR: review-wanted

#237 [GA Skills SDK][Virtual Assistant] Update MainDialog
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
Labels: PR: reviewed-approved

#245 [GA Skills SDK][Virtual Assistant] Fix ESLint issues
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/src/services/botSettings.ts
Labels: PR: reviewed-approved

#247 [GA Skills SDK][Virtual Assistant] Fix build issues
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/src/services/botServices.ts
Labels: PR: changes-requested

#251 [BotBuilder-Solutions] Set default language in SetLocaleMiddleware constructor
  sdk/typescript/libraries/botbuilder-solutions/src/middleware/setLocaleMiddleware.ts
Labels: PR: review-wanted

#253 Fix botServices' cognitiveModelSet
  templates/typescript/samples/sample-assistant/src/services/botServices.ts
Labels: PR: review-wanted

#255 Fix call of onMemberAdded
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
Labels: PR: review-wanted

#260 [GA Skills SDK][Skill] Upgrade ESLint version
  templates/typescript/samples/sample-skill/package-lock.json
  templates/typescript/samples/sample-skill/package.json
  templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
Labels: PR: review-wanted

#256 Fix issues found in mainDialog
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
Labels: PR: reviewed-approved

#261 Fix missing type property in activity
  sdk/typescript/libraries/botbuilder-solutions/src/extensions/activityEx.ts
Labels: PR: reviewed-approved

#266 [Typescript][BB Solutions] Fix empty object validation
  sdk/typescript/libraries/botbuilder-solutions/src/skills/skillConversationIdFactory.ts
Labels: PR: reviewed-approved
