Repository southworks/botframework-solutions, pull requests merged in 2020-11, with the labels that each got.

#458 [Documentation] Update overview section
  docs/_docs/overview/skills.md
  docs/_docs/overview/virtual-assistant-solution.md
  docs/_docs/overview/whats-new/0.7-beta/Summary.md
  docs/_docs/overview/whats-new/0.7-beta/release-notes.md
  docs/_docs/overview/whats-new/0.8-beta/release-notes.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#464 [C#] Add PackageIcon property as PackageIconUrl was deprecated in Directory.Build.Props file
  sdk/csharp/Directory.Build.props
  sdk/csharp/libraries/microsoft.bot.solutions/icon.png
Labels: PR: reviewed-approved, Promoted to Microsoft

#432 [C#][Virtual Assistant] Add yaml file for C# Virtual Assistant sample functional tests
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/README.md
Labels: PR: reviewed-approved, Promoted to Microsoft

#471 [C#] Update BF SDK versions to 4.11.1
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/SkillSample.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  templates/csharp/Skill/Skill/Skill.csproj
  templates/csharp/VA/VA/VA.csproj
Labels: PR: reviewed-approved

#474 [TypeScript][Bot-Solutions] Add the missing parameter outhCredentials in getTokenStatus method in multiProviderAuthDialog class
  sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
  sdk/typescript/libraries/bot-solutions/src/botSettingsBase.ts
Labels: PR: review-wanted

#476 Test/skill ft pipelines problem
  templates/typescript/samples/sample-skill/functional-tests/README.md
  templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
  templates/typescript/samples/sample-skill/functional-tests/sample-skill.yml
Labels: PR: review-wanted

#477 [Documentation] Update Invoke your skill documentation for C#
  docs/_docs/skills/tutorials/create-skill/csharp/8-invoke-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/8-invoke-your-skill.md
  docs/assets/images/virtualAssistant-Skill-communication.png
Labels: PR: reviewed-approved, documentation
