Repository southworks/botframework-solutions, pull requests merged in 2020-10, with the labels that each got.

#410 [BotSkills] Sanitize appsettings skills properties to be case insensitive for list command
  tools/botskills/src/functionality/listSkill.ts
  tools/botskills/src/utils/index.ts
  tools/botskills/src/utils/sanitizationUtils.ts
Labels: PR: reviewed-approved, Promoted to Microsoft

#412 [Botskills] Sanitize appSettings properties for all the commands
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/disconnectSkill.ts
  tools/botskills/src/functionality/listSkill.ts
  tools/botskills/src/functionality/migrateSkill.ts
  tools/botskills/src/functionality/updateSkill.ts
  tools/botskills/test/mocks/appsettings/appsettingsWithUppercase.json
  tools/botskills/test/sanitization.test.js
Labels: PR: reviewed-approved, Promoted to Microsoft

#438 [Documentation] Improve Testing documentation
  docs/_docs/virtual-assistant/handbook/testing.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#457 Update to SDK version 4.10.4
  sdk/typescript/libraries/bot-solutions/package-lock.json
  sdk/typescript/libraries/bot-solutions/package.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
  templates/typescript/samples/sample-assistant/package.json
  templates/typescript/samples/sample-skill/package.json
Labels: PR: changes-requested

#439 [Documentation] Add Update Skill Manifest document
  docs/_docs/skills/tutorials/add-prebuilt-skill/4-update-skill-manifest.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/5-connect-skill.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/6-test-your-skill.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/7-next-steps.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#397 [Documentation] Removing inconsistencies in botskills documentation
  docs/_docs/skills/handbook/add-skills-to-a-virtual-assistant.md
  docs/_docs/skills/handbook/botskills.md
  docs/_docs/skills/tutorials/add-prebuilt-skill/2-download-and-install.md
  docs/_docs/skills/tutorials/create-skill/csharp/2-download-and-install.md
  tools/botskills/README.md
  tools/botskills/docs/commands/connect.md
  tools/botskills/docs/commands/update.md
  tools/botskills/docs/multilanguage-functionality.md
Labels: PR: reviewed-approved, Promoted to Microsoft

#433 [Documentation] Fix ambiguities of TypeScript and C# documentation for manifests
  docs/_docs/skills/tutorials/create-skill/csharp/5-update-manifest.md
  docs/_docs/skills/tutorials/create-skill/typescript/5-update-manifest.md
  docs/_docs/skills/tutorials/create-skill/typescript/6-run-your-skill.md
  docs/_docs/skills/tutorials/create-skill/typescript/7-add-your-skill.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/5-run-your-assistant.md
Labels: PR: reviewed-approved, Promoted to Microsoft

#408 [Virtual Assistant][Skill] Wrap with quotes the zip in the publish scripts
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/publish.ps1
  samples/csharp/skill/SkillSample/Deployment/Scripts/publish.ps1
  templates/csharp/Skill/Skill/Deployment/Scripts/publish.ps1
  templates/csharp/VA/VA/Deployment/Scripts/publish.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/publish.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/publish.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/publish.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/publish.ps1
Labels: PR: reviewed-approved, Promoted to Microsoft

#378 [TypeScript][Generator] Fix broken tests
  templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.test.suite.js
Labels: PR: reviewed-approved, Promoted to Microsoft

#381 [TypeScript][Skill] Fix cognitivemodel mocks values
  templates/typescript/generator-bot-virtualassistant/generators/skill/src/copier.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/resources/cognitiveModels.json
  templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.skill.test.suite.js
Labels: PR: reviewed-approved, Promoted to Microsoft

#447 [C#][Virtual Assistant Sample] Fixing inverted parameters in TokenExchangeSkillHandler.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/TokenExchange/TokenExchangeSkillHandler.cs
Labels: PR: reviewed-approved, Promoted to Microsoft

#452 [C#][VSIX] Fix template placeholder not correctly replaced in Skill yml file
  templates/csharp/Skill/Skill/SkillProjectTemplate.vstemplate
Labels: PR: reviewed-approved, Promoted to Microsoft

#451 [Documentation] Update /overview/virtual-assistant-template/ and fix broken links
  docs/_docs/overview/virtual-assistant-template.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#444 [Documentation] Fix Resturant Booking Skill image
  docs/assets/images/skills-restaurant-transcript.png
Labels: PR: reviewed-approved, Promoted to Microsoft

#446 [Documentation] Fix definition of RemoteToLocal argument of deployment scripts
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
Labels: PR: reviewed-approved, Promoted to Microsoft

#450 [Documentation] Remove Automotive Assistant sample bullet
  docs/_docs/overview/virtual-assistant-solution.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#449 [Documentation] Update Known Issues document adding the dispatch refresh problem
  docs/_docs/help/known-issues.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#459 [C#][Virtual Assistant Template] Fixing inverted parameters in TokenExchangeSkillHandler.cs
  templates/csharp/VA/VA/TokenExchange/TokenExchangeSkillHandler.cs
Labels: PR: reviewed-approved, Promoted to Microsoft

#454 [C# & TypeScript][VA & Skill] Clarify luis section after deploying bots
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/parameters.template.json
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/parameters.template.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/parameters.template.json
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Resources/template.json
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Deployment/Scripts/deploy.ps1
  samples/csharp/skill/SkillSample/Deployment/Resources/parameters.template.json
  samples/csharp/skill/SkillSample/Deployment/Resources/template.json
  samples/csharp/skill/SkillSample/Deployment/Scripts/deploy.ps1
  templates/csharp/Skill/Skill/Deployment/Resources/parameters.template.json
  templates/csharp/Skill/Skill/Deployment/Resources/template.json
  templates/csharp/Skill/Skill/Deployment/Scripts/deploy.ps1
  templates/csharp/VA/VA/Deployment/Resources/parameters.template.json
  templates/csharp/VA/VA/Deployment/Resources/template.json
  templates/csharp/VA/VA/Deployment/Scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/parameters.template.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/parameters.template.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-assistant/deployment/resources/parameters.template.json
  templates/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-skill/deployment/resources/parameters.template.json
  templates/typescript/samples/sample-skill/deployment/resources/template.json
  templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
Labels: PR: reviewed-approved, Promoted to Microsoft
