Repository southworks/botframework-solutions, pull requests merged in 2020-05, with the labels that each got.

#297 Update cognitivemodels.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/cognitivemodels.json
  templates/typescript/samples/sample-assistant/src/cognitivemodels.json
Labels: PR: reviewed-approved

#298 Update onboardingDialog
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/models/stateProperties.ts
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/dialogs/onboardingDialog.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/src/models/stateProperties.ts
Labels: PR: reviewed-approved

#299 Remove locales folder
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/de-de.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/en-us.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/es-es.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/fr-fr.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/it-it.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/locales/zh-cn.json
  templates/typescript/samples/sample-assistant/src/locales/de-de.json
  templates/typescript/samples/sample-assistant/src/locales/en-us.json
  templates/typescript/samples/sample-assistant/src/locales/es-es.json
  templates/typescript/samples/sample-assistant/src/locales/fr-fr.json
  templates/typescript/samples/sample-assistant/src/locales/it-it.json
  templates/typescript/samples/sample-assistant/src/locales/zh-cn.json
Labels: PR: reviewed-approved

#300 Remove templateManager folder
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/dictionaryRenderer.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/graphClient.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/templateManager.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/templateManager/templateRenderer.ts
  templates/typescript/samples/sample-assistant/src/templateManager/dictionaryRenderer.ts
  templates/typescript/samples/sample-assistant/src/templateManager/graphClient.ts
  templates/typescript/samples/sample-assistant/src/templateManager/templateManager.ts
  templates/typescript/samples/sample-assistant/src/templateManager/templateRenderer.ts
Labels: PR: reviewed-approved

#320 [Documentation][Bot-Solutions] Add README
  sdk/typescript/libraries/bot-solutions/README.md
Labels: PR: reviewed-approved, Promoted to Microsoft, documentation

#326 [TypeScript][Bot Solutions] Update dialogs folder
  sdk/typescript/libraries/bot-solutions/src/dialogs/eventPrompt.ts
  sdk/typescript/libraries/bot-solutions/src/dialogs/interruptableDialog.ts
  sdk/typescript/libraries/bot-solutions/src/dialogs/interruptionAction.ts
Labels: PR: review-wanted

#327 [TypeScript][Bot Solutions] Remove responses folder
  sdk/typescript/libraries/bot-solutions/src/skills/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.zh.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/skillResponses.ts
Labels: PR: reviewed-approved

#331 [TypeScript][Bot-Solutions] Remove language from screenResult initialization
  sdk/typescript/libraries/bot-solutions/src/middleware/contentModeratorMiddleware.ts
Labels: PR: reviewed-approved

#332 [TypeScript][Bot-Solutions] Migrate Authentication folder
  sdk/typescript/libraries/bot-solutions/src/authentication/authenticationResponses.ts
  sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.zh.json
Labels: PR: review-wanted, PR: reviewed-approved

#333 [TypeScript][Bot-Solutions] Simplify role validation
  sdk/typescript/libraries/bot-solutions/src/proactive/proactiveStateMiddleware.ts
Labels: PR: reviewed-approved

#328 [TypeScript][Bot Solutions] Update Feedback folder
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackOptions.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.zh.json
Labels: PR: review-wanted

#334 [TypeScript][Bot-Solutions] Migrate BotSettingsBase
  sdk/typescript/libraries/bot-solutions/src/botSettings.ts
  sdk/typescript/libraries/bot-solutions/src/botSettingsBase.ts
  sdk/typescript/libraries/bot-solutions/src/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialog.ts
Labels: PR: reviewed-approved

#335 [TypeScript][Bot-Solutions] Migrate Skills folder
  sdk/typescript/libraries/bot-solutions/src/skills/dialogs/switchSkillDialog.ts
  sdk/typescript/libraries/bot-solutions/src/skills/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/skillEvents.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillConversationIdFactory.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialog.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialogArgs.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillMiddleware.ts
Labels: PR: reviewed-approved
