Repository southworks/botframework-solutions, pull requests merged in 2021-06, with the labels that each got.

#481 [TypeScript][Virtual Assistant & Skill] Fix duplicated messages when communicating through DirectLine
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/bots/_defaultActivityHandler.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/localization.test.js
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/mainDialog.test.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/bots/defaultActivityHandler.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/localization.test.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mainDialog.test.js
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-assistant/test/localization.test.js
  templates/typescript/samples/sample-assistant/test/mainDialog.test.js
  templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-skill/test/localization.test.js
  templates/typescript/samples/sample-skill/test/mainDialog.test.js
Labels: PR: promoted to microsoft, PR: reviewed approved

#462 [Documentation] Update Virtual Assistant section
  docs/_docs/virtual-assistant/handbook/activity-flow.md
  docs/_docs/virtual-assistant/handbook/deployment-scripts.md
  docs/_docs/virtual-assistant/handbook/devops.md
  docs/_docs/virtual-assistant/handbook/localization.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/csharp/4-provision-your-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/2-download-and-install.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/3-create-project.md
  docs/_docs/virtual-assistant/tutorials/create-assistant/typescript/4-provision-you-azure-resources.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/2-edit-your-greeting.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/3-edit-responses.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/2-edit-your-greeting.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/3-edit-responses.md
  docs/_docs/virtual-assistant/tutorials/customize-assistant/typescript/4-edit-your-cognitive-models.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/cli/1-intro.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/cli/4-update-application-settings.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/cli/5-deploy-luis-models.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/cli/7-create-dispatch-model.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/web/1-intro.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/web/4-update-application-settings.md
  docs/_docs/virtual-assistant/tutorials/deploy-assistant/web/7-create-dispatch-model.md
Labels: PR: promoted to microsoft, PR: reviewed approved, documentation

#478 [Documentation] Update Clients and Channels section
  docs/_data/button.yml
  docs/_docs/clients-and-channels/tutorials/enable-speech/4-integrate-speech-channel.md
Labels: PR: promoted to microsoft, PR: reviewed approved, documentation

#482 [C# & TS][VA & Bot-Solutions] Remove FeedbackMiddleware functionality
  docs/_docs/overview/virtual-assistant-template.md
  docs/_docs/overview/whats-new/1.0/Summary.md
  docs/_docs/solution-accelerators/tutorials/enable-proactive-notifications/4-virtual-assistant.md
  docs/_docs/virtual-assistant/handbook/activity-flow.md
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackOptions.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackRecord.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.Designer.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.de.resx
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.es.resx
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.fr.resx
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.it.resx
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.resx
  sdk/csharp/libraries/microsoft.bot.solutions/Feedback/FeedbackResponses.zh.resx
  sdk/csharp/libraries/microsoft.bot.solutions/Microsoft.Bot.Solutions.csproj
  sdk/csharp/tests/microsoft.bot.solutions.tests/Middleware/SetSpeakMiddlewareTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Proactive/ProactiveTests.cs
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackOptions.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackRecord.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackResponses.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/index.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.zh.json
  sdk/typescript/libraries/bot-solutions/src/index.ts
  sdk/typescript/libraries/bot-solutions/test/feedbackMiddleware.test.js
  sdk/typescript/libraries/bot-solutions/test/middleware/setSpeakMiddleware.test.js
  templates/csharp/VA/VA.Tests/BotTestBase.cs
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/adapters/defaultAdapter.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/test/helpers/botTestBase.js
  templates/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-assistant/test/helpers/botTestBase.js
Labels: PR: promoted to microsoft, PR: reviewed approved

#497 [TypeScript][Samples & Templates] Update Deployment Scripts and ARM Templates
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/parameters.template.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/luis_functions.ps1
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/deployment/scripts/update_cognitive_models.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/parameters.template.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/resources/template.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/luis_functions.ps1
  templates/typescript/samples/sample-assistant/deployment/resources/parameters.template.json
  templates/typescript/samples/sample-assistant/deployment/resources/template.json
  templates/typescript/samples/sample-assistant/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/luis_functions.ps1
  templates/typescript/samples/sample-assistant/deployment/scripts/update_cognitive_models.ps1
  templates/typescript/samples/sample-skill/deployment/resources/parameters.template.json
  templates/typescript/samples/sample-skill/deployment/resources/template.json
  templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/luis_functions.ps1
Labels: PR: promoted to microsoft, PR: reviewed approved

#479 [Documentation] Update internal documentation
  samples/android/clients/EventCompanion/readme.md
  samples/csharp/assistants/enterprise-assistant/README.md
  sdk/typescript/libraries/bot-solutions/README.md
  templates/csharp/README.md
  templates/csharp/Skill/Skill/readme.md
  templates/csharp/VA/VA/readme.md
  templates/typescript/generator-bot-virtualassistant/README.md
  templates/typescript/generator-bot-virtualassistant/generators/app/README.md
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/README.md
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/pipeline/README.md
  templates/typescript/generator-bot-virtualassistant/generators/skill/README.md
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/README.md
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/pipeline/README.md
  templates/typescript/samples/sample-assistant/README.md
  templates/typescript/samples/sample-assistant/pipeline/README.md
  templates/typescript/samples/sample-skill/README.md
  templates/typescript/samples/sample-skill/pipeline/README.md
  tools/botskills/README.md
  tools/botskills/docs/commands/connect.md
  tools/botskills/docs/commands/disconnect.md
  tools/botskills/docs/commands/list.md
  tools/botskills/docs/commands/migrate.md
  tools/botskills/docs/commands/refresh.md
  tools/botskills/docs/commands/update.md
Labels: PR: promoted to microsoft, PR: reviewed approved, documentation

#496 [Documentation] Detail the code changes after adding a new Knowledge Base
  docs/_docs/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models.md
Labels: PR: promoted to microsoft, PR: reviewed approved

#348 [TypeScript][Bot-Solutions] Implement changes in Bot-Solutions to 1.0 release
  sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
  sdk/typescript/libraries/bot-solutions/src/botSettings.ts
  sdk/typescript/libraries/bot-solutions/src/botSettingsBase.ts
  sdk/typescript/libraries/bot-solutions/src/dialogs/eventPrompt.ts
  sdk/typescript/libraries/bot-solutions/src/dialogs/interruptableDialog.ts
  sdk/typescript/libraries/bot-solutions/src/dialogs/interruptionAction.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/activityEx.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/dateTimeEx.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/dialogContextEx.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/dialogEx.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/index.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/listEx.ts
  sdk/typescript/libraries/bot-solutions/src/extensions/luisRecognizerEx.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/feedbackOptions.ts
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.json
  sdk/typescript/libraries/bot-solutions/src/feedback/resources/FeedbackResponses.zh.json
  sdk/typescript/libraries/bot-solutions/src/index.ts
  sdk/typescript/libraries/bot-solutions/src/middleware/contentModeratorMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/proactive/proactiveStateMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/responses/speechUtility.ts
  sdk/typescript/libraries/bot-solutions/src/skills/dialogs/switchSkillDialog.ts
  sdk/typescript/libraries/bot-solutions/src/skills/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/models/skillEvents.ts
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/resources/SkillResponses.zh.json
  sdk/typescript/libraries/bot-solutions/src/skills/responses/skillResponses.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillConversationIdFactory.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialog.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillDialogArgs.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/util/responsesUtil.ts
  sdk/typescript/libraries/bot-solutions/test/feedbackMiddleware.test.js
  sdk/typescript/libraries/bot-solutions/test/proactive/proactive.test.js
  sdk/typescript/libraries/bot-solutions/test/responses/languageGeneration.test.js
  sdk/typescript/libraries/bot-solutions/test/skillMiddleware.test.js
Labels: PR: promoted to microsoft, PR: reviewed approved, parity

#399 [TypeScript][Skill] Implement changes in Skill to 1.0 release
  templates/typescript/generator-bot-virtualassistant/generators/skill/src/copier.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_.eslintrc.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/deployment/scripts/luis_functions.ps1
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/_cognitivemodels.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/appsettings.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/authentication/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/bots/defaultActivityHandler.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/dialogs/_mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/dialogs/sampleAction.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/dialogs/sampleDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/dialogs/skillDialogBase.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/extensions/turnContextEx.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/services/botServices.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/services/botSettings.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/helpers/skillTestBase.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/interruption.test.js
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/interruption_cancel_response.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/interruption_help_response.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/mainDialog_help_response.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/mainDialog_unhandled_response.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/test/mocks/nockFixtures/sampleDialog_response.json
  templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.skill.test.suite.js
  templates/typescript/samples/sample-skill/.eslintrc.json
  templates/typescript/samples/sample-skill/deployment/scripts/deploy.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/deploy_cognitive_models.ps1
  templates/typescript/samples/sample-skill/deployment/scripts/luis_functions.ps1
  templates/typescript/samples/sample-skill/package-lock.json
  templates/typescript/samples/sample-skill/package.json
  templates/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-skill/src/appsettings.json
  templates/typescript/samples/sample-skill/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/samples/sample-skill/src/authentication/index.ts
  templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-skill/src/cognitivemodels.json
  templates/typescript/samples/sample-skill/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-skill/src/dialogs/sampleAction.ts
  templates/typescript/samples/sample-skill/src/dialogs/sampleDialog.ts
  templates/typescript/samples/sample-skill/src/dialogs/skillDialogBase.ts
  templates/typescript/samples/sample-skill/src/extensions/turnContextEx.ts
  templates/typescript/samples/sample-skill/src/index.ts
  templates/typescript/samples/sample-skill/src/services/botServices.ts
  templates/typescript/samples/sample-skill/src/services/botSettings.ts
  templates/typescript/samples/sample-skill/test/helpers/skillTestBase.js
  templates/typescript/samples/sample-skill/test/interruption.test.js
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/interruption_cancel_response.json
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/interruption_help_response.json
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/mainDialog_help_response.json
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/mainDialog_unhandled_response.json
  templates/typescript/samples/sample-skill/test/mocks/nockFixtures/sampleDialog_response.json
Labels: PR: promoted to microsoft, PR: reviewed approved, parity

#401 [Generator & Botskills] Fix dependencies' vulnerabilities
  templates/typescript/generator-bot-virtualassistant/package-lock.json
  templates/typescript/generator-bot-virtualassistant/package.json
  tools/botskills/package-lock.json
Labels: PR: promoted to microsoft, PR: reviewed approved

#423 [C#][Bot-Solutions] Add System.Obsolete in the LuisService implementation of BotSettingsBase
  sdk/csharp/libraries/microsoft.bot.solutions/BotSettingsBase.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Services/ConnectedService.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Services/LuisService.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Services/QnAMakerService.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Services/ServiceTypes.cs
Labels: PR: promoted to microsoft, PR: reviewed approved

#430 [PORT #3262][Botskills] Show all language output when there's an issue with a LU file
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/test/connect.test.js
Labels: PR: promoted to microsoft, PR: reviewed approved

#495 [Bot-Solutions] [TypeScript] Fix MultiProviderAuthDialog localization
  sdk/typescript/libraries/bot-solutions/src/authentication/authenticationResponses.ts
  sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.de.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.es.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.fr.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.it.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.json
  sdk/typescript/libraries/bot-solutions/src/authentication/resources/AuthenticationResponses.zh.json
  sdk/typescript/libraries/bot-solutions/src/responses/responseManager.ts
Labels: PR: promoted to microsoft, PR: reviewed approved

#499 [TypeScript][Bot-Solutions] Add missing dependencies
  sdk/typescript/libraries/bot-solutions/package-lock.json
  sdk/typescript/libraries/bot-solutions/package.json
Labels: PR: promoted to microsoft, PR: reviewed approved

#411 [TypeScript][Skill] Add manifest endpoint
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/samples/sample-skill/src/index.ts
Labels: PR: promoted to microsoft, PR: reviewed approved

#422 [C#][VA & Skill] Replace AzureBlobTranscriptStore references to BlobsTranscriptStore
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  templates/csharp/Skill/Skill/Adapters/DefaultAdapter.cs
  templates/csharp/VA/VA/Adapters/DefaultAdapter.cs
Labels: PR: promoted to microsoft, PR: reviewed approved

#456 [Botskills] Unit Test compability for Linux
  tools/botskills/src/functionality/connectSkill.ts
  tools/botskills/src/functionality/disconnectSkill.ts
  tools/botskills/src/functionality/listSkill.ts
  tools/botskills/src/functionality/migrateSkill.ts
  tools/botskills/src/functionality/refreshSkill.ts
  tools/botskills/src/functionality/updateSkill.ts
  tools/botskills/src/utils/authenticationUtils.ts
  tools/botskills/src/utils/azUtils.ts
  tools/botskills/src/utils/manifestUtils.ts
  tools/botskills/src/utils/sanitizationUtils.ts
  tools/botskills/test/authentication.test.js
  tools/botskills/test/childProcess.test.js
  tools/botskills/test/connect.test.js
  tools/botskills/test/disconnect.test.js
  tools/botskills/test/list.test.js
  tools/botskills/test/mocks/appsettings/noAuthConnectionAppsettings.json
  tools/botskills/test/refresh.test.js
  tools/botskills/test/sanitization.test.js
  tools/botskills/test/update.test.js
Labels: PR: promoted to microsoft, PR: reviewed approved

#501 [TypeScript] Changes in TypeScript components for deprecation plan
  sdk/typescript/libraries/bot-solutions/package-lock.json
  sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/dialogs/skillDialogBase.ts
  templates/typescript/generator-bot-virtualassistant/package-lock.json
  templates/typescript/generator-bot-virtualassistant/package.json
  templates/typescript/generator-bot-virtualassistant/test/generator-bot-virtualassistant.test.suite.js
  templates/typescript/samples/sample-assistant/deployment/resources/Skills/emailskill/en-us/Email.lu
  templates/typescript/samples/sample-assistant/deployment/resources/Skills/pointofinterestskill/en-us/PointOfInterest.lu
  templates/typescript/samples/sample-assistant/deployment/resources/Skills/pointofinterestskill/en-us/secondary/poi_navigation_find_parking.lu
  templates/typescript/samples/sample-assistant/deployment/resources/Skills/pointofinterestskill/en-us/secondary/poi_navigation_find_poi.lu
  templates/typescript/samples/sample-assistant/deployment/resources/Skills/pointofinterestskill/en-us/secondary/poi_navigation_get_directions.lu
  templates/typescript/samples/sample-assistant/deployment/resources/Skills/todoskill/en-us/ToDo.lu
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-assistant/test/helpers/botTestBase.js
  templates/typescript/samples/sample-skill/src/dialogs/skillDialogBase.ts
  tools/botskills/test/connect.test.js
  tools/botskills/test/refresh.test.js
Labels: PR: review wanted

#506 [C#] Update templates
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Authentication/AllowedCallersClaimsValidator.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/enterprise-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample.Tests/BotTestBase.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Authentication/AllowedCallersClaimsValidator.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/hospitality-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Authentication/AllowedCallersClaimsValidator.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
  samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
  samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs
  samples/csharp/skill/SkillSample/SkillSample.csproj
  sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
  sdk/csharp/libraries/microsoft.bot.solutions/Skills/SkillConversationIdFactory.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Middleware/SetSpeakMiddlewareTests.cs
  sdk/csharp/tests/microsoft.bot.solutions.tests/Skills/SkillConversationIdFactoryTests.cs
  templates/csharp/Skill/Skill/Adapters/DefaultAdapter.cs
  templates/csharp/Skill/Skill/Authentication/AllowedCallersClaimsValidator.cs
  templates/csharp/Skill/Skill/Skill.csproj
  templates/csharp/Skill/Skill/Startup.cs
  templates/csharp/VA/VA/Adapters/DefaultAdapter.cs
  templates/csharp/VA/VA/Authentication/AllowedCallersClaimsValidator.cs
  templates/csharp/VA/VA/VA.csproj
Labels: PR: review wanted

#505 [TypeScript] Upgrade to last SDK
  sdk/typescript/libraries/bot-solutions/package-lock.json
  sdk/typescript/libraries/bot-solutions/package.json
  sdk/typescript/libraries/bot-solutions/src/botSettingsBase.ts
  sdk/typescript/libraries/bot-solutions/src/middleware/index.ts
  sdk/typescript/libraries/bot-solutions/src/middleware/setSpeakMiddleware.ts
  sdk/typescript/libraries/bot-solutions/src/skills/index.ts
  sdk/typescript/libraries/bot-solutions/src/skills/skillConversationIdFactory.ts
  sdk/typescript/libraries/bot-solutions/test/middleware/setSpeakMiddleware.test.js
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/adapters/defaultAdapter.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/bots/defaultActivityHandler.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/_package.json
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/authentication/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/index.ts
  templates/typescript/generator-bot-virtualassistant/generators/skill/templates/sample-skill/src/services/botServices.ts
  templates/typescript/generator-bot-virtualassistant/package-lock.json
  templates/typescript/generator-bot-virtualassistant/package.json
  templates/typescript/samples/sample-assistant/package.json
  templates/typescript/samples/sample-assistant/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-assistant/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/samples/sample-assistant/src/bots/defaultActivityHandler.ts
  templates/typescript/samples/sample-assistant/src/dialogs/mainDialog.ts
  templates/typescript/samples/sample-assistant/src/index.ts
  templates/typescript/samples/sample-skill/package.json
  templates/typescript/samples/sample-skill/src/adapters/defaultAdapter.ts
  templates/typescript/samples/sample-skill/src/authentication/allowedCallersClaimsValidator.ts
  templates/typescript/samples/sample-skill/src/authentication/index.ts
  templates/typescript/samples/sample-skill/src/index.ts
  templates/typescript/samples/sample-skill/src/services/botServices.ts
Labels: PR: review wanted

#509 [C#][VA/Skill] Replicate changes of Samples to Templates
  templates/csharp/Skill/Skill/Services/BotServices.cs
  templates/csharp/Skill/Skill/Services/BotSettings.cs
  templates/csharp/Skill/Skill/SkillProjectTemplate.vstemplate
  templates/csharp/Skill/Skill/Startup.cs
  templates/csharp/Skill/Skill/appsettings.json
  templates/csharp/VA/VA.Tests/BotTestBase.cs
  templates/csharp/VA/VA.Tests/VA.Tests.csproj
  templates/csharp/VA/VA/Bots/DefaultActivityHandler.cs
  templates/csharp/VA/VA/Dialogs/MainDialog.cs
  templates/csharp/VA/VA/Extensions/InvokeActivityExtensions.cs
  templates/csharp/VA/VA/Extensions/InvokeResponseExtensions.cs
  templates/csharp/VA/VA/Models/SkillCardActionData.cs
  templates/csharp/VA/VA/Services/BotServices.cs
  templates/csharp/VA/VA/Services/BotSettings.cs
  templates/csharp/VA/VA/Startup.cs
  templates/csharp/VA/VA/VA.csproj
  templates/csharp/VA/VA/VAProjectTemplate.vstemplate
  templates/csharp/VA/VA/appsettings.json
Labels: PR: promoted to microsoft, PR: reviewed approved

#510 [TypeScript][Virtual Assistant] Add claim's validation if the VA is not connected to Skills
  templates/typescript/generator-bot-virtualassistant/generators/app/templates/sample-assistant/src/index.ts
  templates/typescript/samples/sample-assistant/src/index.ts
Labels: PR: promoted to microsoft, PR: reviewed approved

#511 [TypeScript][Samples] Update package-lock to consume last version of bot-solutions 1.1.0
  templates/typescript/samples/sample-assistant/package-lock.json
  templates/typescript/samples/sample-skill/package-lock.json
Labels: PR: promoted to microsoft, PR: reviewed approved
